apiVersion: v1
kind: Service
metadata:
  name: seoul-frontend
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/contents"
  labels:
    env: dev
spec:
  selector:
    app: seoul-frontend
